### ISSUE TITLE
This doesn't work anymore with the latest Flutter/Dart master branch

### ISSUE THREAD

**Issue by ganeshrvel** [mraleph/go_dart_ffi_example#4]
This example doesn't work anymore with the latest Flutter/Dart master branch.

Running the code in this repo now throws:
```
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x0
../../third_party/dart/runtime/vm/os_thread.cc: 58: error: expected: HasStackHeadroom()
Aborting re-entrant request for stack trace.
/Users/username/Library/Application Support/fvm/versions/master/bin/internal/shared.sh: line 224: 86913 Abort trap: 6           "$DART" "$@"
````

`flutter --version` output:
```
Flutter 1.26.0-2.0.pre.251 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5bc725bea8 (5 hours ago) • 2021-01-08 08:12:36 +0100
Engine • revision 2e5833b7c5
Tools • Dart 2.12.0 (build 2.12.0-179.0.dev)
```

How do we fix this?

**Comment by marchellodev** [comment]
+, Is there any way to fix this? @ganeshrvel Your fix does not seem to work anymore :)

**Comment by mraleph** [comment]
You need to keep `dart_api_dl/include` in sync with Dart SDK version. 

I have updated the example and made this requirement clear. It should now work with most recent versions of Dart (but conversly it does not work with older versions).

**Comment by marchellodev** [comment]
Thanks for the explanation!
